stages:
  prepare:
    cmd: uv run python src/data/prepare_dataset.py
    deps:
      - data/balanced_gold
      - src/data/prepare_dataset.py
    outs:
      - data/raw

  train:
    cmd: uv run python src/ml/training/train.py
    deps:
      - configs/
      - data/raw
      - src/ml/data/dataloader.py
      - src/ml/evaluation/evaluator.py
      - src/ml/models/model.py
      - src/ml/training/train.py
      - src/ml/training/trainer.py
    outs:
      - models/model.pth
