name: mobilenet_v2
pretrained: true
num_classes: 4
unfreeze_last_n: 5
checkpoint_path: models/model.pth

peft:
  method: lora  # lora or dora
  r: 8
  alpha: 16
  dropout: 0.1
  target_modules:
    - features.14.conv.0
    - features.15.conv.0
    - features.16.conv.0
